### ISSUE TITLE
Prevent over-eating

### ISSUE THREAD

**Issue by tacotexmex** [4w/hunger_ng#7]
Don’t let players consume food when satiated.

**Comment by 4w** [comment]
But how decide if the player is satiated?

Since the hunger value is ceiled for display (all above 19 looks like 20) full hunger bar does not mean the player is fully satiated. So the ceiled value can't be seen as being satiated.

The healing value can't be used as being satiated either, because it is lower than the maximum value and players won't be able to get to the value when stopping at the healing value.

The unceiled value won't be useful because due to basal metabolism and movement-dependent hunger costs it won't stay at maximum for some time.

**Comment by tacotexmex** [comment]
Not sure. But it's weird that players may consume 99 loafs of bread as fast as they can click.

**Comment by 4w** [comment]
Maybe having an attribute storing a timestamp of when the player ate something the last time and allow eating every N seconds only. This would not prevent overeating but would work a little against (accidental) rightclick spam.

**Comment by 4w** [comment]
Overeating has no exact value to measure so a timeout will be implemented.

See #10 for further development.
