### ISSUE TITLE
Eating effects

### ISSUE THREAD

**Issue by tacotexmex** [4w/hunger_ng#8]
Particles, sounds?

**Comment by 4w** [comment]
Since there is no eating animation eating particles would be useless 😄

[Sounds are already there](https://github.com/4w/hunger_ng/tree/72b7bdda40be62c00b372d91978bf644dc2915a5/sounds). [They play](https://github.com/4w/hunger_ng/blob/72b7bdda40be62c00b372d91978bf644dc2915a5/system/register_on.lua#L56) when players eat compatible food. Feel free to suggest new sounds.

**Comment by tacotexmex** [comment]
> Since there is no eating animation eating particles would be useless 😄

I think that both from a 1st person and a 3rd person view, visual feedback of eating would increase immersion.

**Comment by 4w** [comment]
It would, yes. But I am absolutely not sure if it is possible.

**Comment by tacotexmex** [comment]
I'm thinking of something like how MineClone2 does it. (particle spawner from the lower part of the player head)

**Comment by 4w** [comment]
The particle spawner itself wouldn't be that much of a problem. The question is: how would we get something that looks like an eating animation without re-implementing large portions of `default`?

**Comment by tacotexmex** [comment]
Character animation seems futile given the current woes of player model animation.

**Comment by 4w** [comment]
Yep :(

I tend to close this because the mod already has sounds and with the current engine proper eating animations are not possible. Maybe one day someone comes up with a new fully animatable player model ...

**Comment by tacotexmex** [comment]
And the particles? See [this image](https://proxy.spigotmc.org/733163acb52e2c04e076efa9c079635532777e8c?url=http%3A%2F%2Fi.imgur.com%2FMrJhpkO.png) and [this clip](https://youtu.be/MQ1BYiPJr_E?t=25s) for a suggestion.

**Comment by 4w** [comment]
To me eating particles make no sense without an animation that looks at least a little like the player actually eating something. I'll check how it looks and if it worth the extra code.

**Comment by 4w** [comment]
Spawning particles is no problem at all but while the particle spawner [can be defined relative to the player](https://github.com/minetest/minetest/blob/e7f16119913f7b2c98059398085d410684c9d8c0/doc/lua_api.txt#L5357L5359) there seems to be no way to make **particles** relative to the player.

This results in particles looking okay-ish when standing and not looking around but the particles being completely out of location when looking around or moving because the position of the particle spawner does not change fast enough after starting it and the particles are not relative to the player even if the particle spawner is.

With the current Minetest modding API particles won’t be added, sorry.
